config/routes.rb
Rails.application.routes.draw do

  # resources :user
  resource :users
  get '/hotkeys/index' => 'hotkeys#index', as: :hotkeys #creates hotkeys_path
  get '/users' => 'users#show', as: :user_root # creates user_root_path
  resource :sessions
  resources :programs do
    resources :hotkeys do
      member do
        post 'add_favorite'
        delete 'remove_favorite'
      end
    end
  end
  root "welcomes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :hotkey

end

app/models/hotkey.rb
class Hotkey < ApplicationRecord
  belongs_to :program
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :hotkeys, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites
  has_many :hotkeys, through: :favorites
  def get_sorted_favorites
    @sort_favorites = {}
    programs = []
    self.favorites.each do |favorite|
      if !(programs.include?(favorite.hotkey.program))
        programs << favorite.hotkey.program
      end
    end
    user = self
    programs.each do |program|
      hotkeys = []
      user.favorites.each do |favorite|
        if program.name == favorite.hotkey.program.name
          hotkeys << favorite.hotkey
        end
      end
      @sort_favorites[program] = hotkeys
    end
    @sort_favorites
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  def set_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/hotkeys_controller.rb
class HotkeysController < ApplicationController
  before_action :get_hotkey, only: [:show, :edit, :update, :destroy, :add_favorite, :remove_favorite]

  def get_hotkey
    @hotkey = Hotkey.find(params[:id])
  end

  def add_favorite
    @favorite = Favorite.create!(user: @current_user, hotkey: @hotkey)
    @hotkey.numOfFavorite += 1
    @hotkey.save
    redirect_to programs_path
  end

  def remove_favorite
    @favorite = Favorite.find_by(user: @current_user, hotkey: @hotkey)
    @favorite.destroy
    @hotkey.numOfFavorite += 1
    redirect_to programs_path
  end

  def index
    redirect_to root_path unless @current_user
    @hotkeys = Hotkey.all
  end


  def new
    redirect_to root_path unless @current_user
    @hotkey = Hotkey.new
    @program = Program.find(params[:program_id])
  end

  def edit
    redirect_to root_path unless @current_user
    @program = Program.find(params[:program_id])
  end

  def create
    if params[:hotkey][:name] == ""
      flash[:alert] = "Name can't be blank!"
      redirect_to new_program_path
    else
      hotkey = Hotkey.new(hotkey_params)
      hotkey.program_id = params[:program_id]
      if hotkey.save
        flash[:notice] = "Hotkey was successfully saved!"
        redirect_to program_path(params[:program_id])
      else
        render :new
      end
    end
  end

  def destroy
    @hotkey.destroy
    redirect_to program_path(params[:program_id])
  end

  def update
    @hotkey.update(hotkey_params)
    @program = Program.find(params[:program_id])
    redirect_to @program
  end

  private
  def hotkey_params
    params.require(:hotkey).permit(:name, :function)
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
    redirect_to root_path unless @current_user
    @programs = Program.all
  end

  def show
    redirect_to root_path unless @current_user
    @program = Program.find(params[:id])
  end

  def edit
    redirect_to root_path unless @current_user
    @program = Program.find(params[:id])
  end

  def new
    @program = Program.new
  end

  def destroy
  end

  def create
    @program = Program.create!(program_params)
    redirect_to programs_path
  end

  private
  def program_params
    params.require(:program).permit(:name, :version)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
      if @user.password == params[:user][:password]
        flash[:notice] = "Sign-in was successful!"
        session[:user_id] = @user.id
        redirect_to users_path(@user)
      else
        flash[:alert] = "Password was incorrect. Sign in failed"
        redirect_to = new_sessions_path
      end
    else
      flash[:alert] = "That user does not exist!"
      redirect_to new_sessions_path
    end
  end

    def destroy
      reset_session
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    unless @current_user
      redirect_to root_path @current_user
    else
      @sort_favorites = @current_user.get_sorted_favorites
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id
    redirect_to user_root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotkeys_helper.rb
module HotkeysHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/hotkeys/_form.html.erb
<%= form_for [@program, @hotkey]  do |f| %>
  <div class='field'>
  <%= f.label :keystrokes %>
  <%= f.text_field :keystrokes %>
  </div>

  <div class='field'>
  <%= f.label :description %>
  <%= f.text_area :description %>
  </div>

  <div class='field'>
  <%= f.submit %>
  </div>

<% end %>

<% @hotkey.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

app/views/hotkeys/edit.html.erb
<h2>Edit Hotkeys</h2>
<%= render 'form' %>

app/views/hotkeys/index.html.erb
<div id="programs">
    <div class="program">
      <div class="program-name">
      <h2>Popular Shortcuts</h2><h3>									Click on the blue bar to expand<h3>
      </div>
      <div class="hotkey-titles" id="hotkey-titles">
        <div class="hotkey-details">
          <h3>Keystroke</h3>
        </div>
        <div class="hotkey-details">
          <h3>Description</h3>
        </div>
        <div class="hotkey-details">
          <h3>Number of Favorites</h3>
        </div>
      </div>
      <% @hotkeys.order(:numOfFavorite).reverse.each do |hotkey| %>
            <div class="hotkey-titles2">
              <div class="hotkey-details">
                <p><%= hotkey.keystrokes %></p>
              </div>
              <div class="hotkey-details">
                <p><%= hotkey.description %></p>
              </div>
              <div class="hotkey-details">
                <p><%= hotkey.numOfFavorite %></p>
                <% if @current_user.hotkeys.include?(hotkey) %>
                  <p><%= link_to '&#x2665'.html_safe, remove_favorite_program_hotkey_path(hotkey.program, hotkey), method: :delete, :class => "fave" %></p>
                <% else %>
                  <p><%= link_to 'Add to Favorites', add_favorite_program_hotkey_path(hotkey.program, hotkey), method: :post %></p>
                <% end %>
              </div>
            </div>
      <% end %>
  </div>
</div>
<script> 
if (!programs){
  let programs;
} 
programs = document.getElementsByClassName('program-name')
for (let i = 0; i < programs.length; i++){
  programs[i].addEventListener("click", () => visibilityFunc(event.target))
}
function visibilityFunc(program) {
  let nodeList = program.parentNode.childNodes
  console.log(nodeList)
  for (let j=5; j < nodeList.length; j++){
    let x = nodeList[j]
    console.log(x.style)
    if (x.style !== undefined && x.style.display === ''){
      console.log("hit1")
      x.style.display = 'flex'
    }else if(x.style !== undefined && x.style.display === 'flex'){
      console.log("hit2")
      x.style.display = ''
    }
    else {
      console.log("hit3")
    }
  }
}
</script>

app/views/hotkeys/new.html.erb
<h2>New Hotkey</h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotkeys</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
<nav id="header">
	<div class="left">
	<h1 class="logo">Shortcuts</h1>
	<% if @current_user %>
	<% else %>
	<div class="tag">Sign in first in order to use application</div>
	<% end %>
	</div>
	
	<div class="right">
	
<div class="sign-in-notice">
    <% if @current_user %>
    Welcome, <%= @current_user.username %>!<br/>
    <%= link_to "Sign Out", sessions_path, method: :delete %>
    <% else %>
    <%= link_to "Sign In", new_sessions_path %>
    <%= link_to "Sign Up", new_users_path %>
    <% end %>
</div>
</div>
</nav>
</header>

<main>
  <div class="container">
    <div class="row">
      <h4 class="title">Links</h4>
      <nav>
        <ul>
		  <li><%= link_to 'Programs', programs_path %></li>
		  <li><%= link_to 'Favorites', user_root_path %></li>
		  <li><%= link_to 'Popular Shortcuts', hotkeys_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</main>

  <% flash.each do |type, message| %>
  <p class="flash <%= type %>"><%= message %></p>
  <% end %>
    <%= yield %>


  </body>
</html>

app/views/programs/_form.html.erb
<%= form_for @program do |f| %>

  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>

  <div class="field">
  <%= f.submit %>
</div>

<% end %>

app/views/programs/edit.html.erb
<h2>Edit Programs</h2>
<%= render 'form' %>

app/views/programs/index.html.erb
<div id="new-program"><%= link_to "Add Program", new_program_path %></div>

<div id="programs">
	<% @programs.each do |program| %>
      <div class="program">
        <div class="program-name">
        <h2 style="display: inline-block;"><%= program.name %></h2>
        <h2 style="display: inline-block; float: right; text-decoration: none"><%= link_to 'Add Hotkey', new_program_hotkey_path(program) %></h2>
        <h3>Click on this blue bar to expand</h3>
		</div>
        <div class="hotkey-titles" id="hotkey-titles">
          <div class="hotkey-details">
            <h3>Keystroke</h3>
          </div>
          <div class="hotkey-details">
          	<h3>Description</h3>
          </div>
          <div class="hotkey-details">
            <h3>Favorites / Remove From Hotkeys</h3>
          </div>
        </div>
    <% program.hotkeys.order(:description).each do |hotkey| %>
        <div class="hotkey-titles2"> 
 	    <div class="hotkey-details">
           <p><%= hotkey.keystrokes %></p>
           </div>
            <div class="hotkey-details">
              <p><%= hotkey.description %></p>
            </div>
            <div class="hotkey-details">
              <p><%= link_to "Remove Hotkey", program_hotkey_path(program, hotkey), method: :delete %>
              <% if @current_user.hotkeys.include?(hotkey) %>
                <p><%= link_to '&#x2665'.html_safe, remove_favorite_program_hotkey_path(program.id, hotkey.id), method: :delete, :class => "fave" %></p>
              <% else %>
                <p><%= link_to 'Add to Favorites', add_favorite_program_hotkey_path(program.id, hotkey.id), method: :post %></p>
              <% end %>
            </div>
          </div>
      <% end %>
  </div>
  <% end %>
</div>
<script> 
if (!programs){
	let programs;
} 
programs = document.getElementsByClassName('program-name')
for (let i = 0; i < programs.length; i++){
	programs[i].addEventListener("click", () => visibilityFunc(event.target))
}
function visibilityFunc(program) {
	let nodeList = program.parentNode.childNodes
	for (let j=5; j < nodeList.length; j++){
		let x = nodeList[j]
		console.log(x.style)
		if (x.style !== undefined && x.style.display === ''){
			console.log("hit1")
			x.style.display = 'flex'
		}else if(x.style !== undefined && x.style.display === 'flex'){
			console.log("hit2")
			x.style.display = ''
		}
		else {
			console.log("hit3")
		}
	}
}
</script>

app/views/programs/new.html.erb
<h1>New Program</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>

  <% end %>

app/views/users/show.html.erb
<h1>Favorites</h1>
<div id="programs">
  <% @sort_favorites.each do |program, hotkeys| %>
    <div class="program">
      <div class="program-name">
      <h2 style="display:inline-block;"><%= program.name %></h2><h3>Click on this blue bar to expand</h3>
      </div>
      <div class="hotkey-titles" id="hotkey-titles">
        <div class="hotkey-details">
          <h3>Keystroke</h3>
        </div>
        <div class="hotkey-details">
          <h3>Description</h3>
        </div>
        <div class="hotkey-details">
          <h3>Remove from Favorites</h3>
        </div>
      </div>
      <% hotkeys.each do |hotkey| %>
            <div class="hotkey-titles2">
              <div class="hotkey-details">
                <p><%= hotkey.keystrokes %></p>
              </div>
              <div class="hotkey-details">
                <p><%= hotkey.description %></p>
              </div>
              <div class="hotkey-details">
                <p><%= link_to 'Remove from Favorites', remove_favorite_program_hotkey_path(hotkey.program, hotkey), method: :delete %></p>
              </div>
            </div>
      <% end %>
  </div>
  <% end %>
</div>
<script>
console.log("hit5")
if (!programs){
let programs;
} 
programs = document.getElementsByClassName('program-name')
for (let i = 0; i < programs.length; i++){
  console.log("hit4")
  programs[i].addEventListener("click", () => visibilityFunc(event.target))
}
function visibilityFunc(program) {
  let nodeList = program.parentNode.childNodes
  console.log(nodeList)
  for (let j=5; j < nodeList.length; j++){
    let x = nodeList[j]
    console.log(x.style)
    if (x.style !== undefined && x.style.display === ''){
      x.style.display = 'flex'
    }else if(x.style !== undefined && x.style.display === 'flex'){
      x.style.display = ''
    }
    else {
    }
  }
}
</script>

app/views/welcomes/index.html.erb
<!-- <div id = "sign_up"><%= link_to 'Sign Up', new_users_path %></div>
<div id = "sign_in"><%= link_to 'Sign In', new_sessions_path %></div> -->